### ISSUE TITLE
Syntax error: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by AndrWeisR** [Slickytail/stable-diffusion-compositional#1]
I had to install a few modules to get this far, the last of which was `pip install ldm`. Then I got:

python 3.9.12 in Anaconda on Windows:

```
(base) C:\Users\andre\stable-diffusion-compositional>python scripts/txt2img.py --prompt "A photo of Barack Obama :: A photo of Joe Biden"
Traceback (most recent call last):
  File "C:\Users\andre\stable-diffusion-compositional\scripts\txt2img.py", line 14, in <module>
    from ldm.util import instantiate_from_config
  File "C:\Users\andre\anaconda3\lib\site-packages\ldm.py", line 20
    print self.face_rec_model_path
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?
```

**Comment by AndrWeisR** [comment]
I renamed the environment in environment.yaml to keep it separate from my existing ldm environment, and then it worked.
